services:
  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - postgres
      - migrate

  migrate:
    build:
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - postgres
    command: [ "uv", "run", "alembic", "upgrade", "head" ]

  postgres:
    image: postgres:13.3
    env_file:
      - .env